# Welcome to Jekyll!
#
# Toto je soubor s hlavním nastavením. Na začátku je nastavení proměných, které
# je třeba přispůsobit si pro váš web. Později v anglicky popsané části jsou více
# technické nastavení
#

title: Plán Pirátů Vodu řešíme teď # To co je napsané na tabu ve kterém je stránka.
email: info@pirati.cz
description: >-
  Plán Pirátů Vodu řešíme teď
keywords: piráti, česká pirátská strana, Vodu řešíme teď, sucho, povodně, vodohospodářství


administrator:
  email: marek.krejpsky@gmail.com # mail(y), kam pujdou chybove vystupy; vice e-mailu oddelujte carkou

organization:
  name: Plán Pirátů Vodu řešíme teď
  shortName: voduresimeted
  email: info@pirati.cz
  address: |
    Na Moráni 3,
    120 00 Praha 2
  residenceImg:
  mapLink: https://mapy.cz/zakladni?vlastni-body&x=14.4418976&y=50.0863156&z=18&ut=PiCe&uc=9h2F.xXwtn&ud=ulice%20%C5%98eho%C5%99ova%20943%2F19%2C%20Praha%2C%20130%2000%2C%20okres%20Hlavn%C3%AD%20m%C4%9Bsto%20Praha
  redmineLink: https://redmine.pirati.cz/projects
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010

# Nastavení zobrazení tabulky kontaktů.
# Lze využít:
# 1) předdefinované typy (organizationEmail, organizationRedmineLink, organizationPhone, organizationTransparentAccount, organizationDataBox, piratiRootWebsite)
# 2) vlastní řádky - zde je nutné jako type dát `custom` a vyplnit `label` a `body`
contactSummaryItems:
  - type: organizationEmail
  - type: organizationRedmineLink
  - type: organizationPhone
  - type: organizationTransparentAccount
    includeMoreLink: true
  - type: organizationDataBox
  - type: piratiRootWebsite
  - type: custom
    iconClass: fa fa-envelope
    label: Vlastní řádek tabulky
    body: <a href="http://example.com">link</a>

calendar:
  # For nice look of the calendar, make sure you get Google Calendar API key
  # and start the app with the env var `GOOGLE_CALENDAR_APIKEY=[myapikey] bundle exec jekyll serve`.
  # For deployment, contact website administrator to set you env variable.
  title: Celostátní kalendář

facebook:
  loadSDK: true
  #vyplně adresu vaší stranky, funguje pouze na stránky nikoliv skupiny
  profilePage: https://www.facebook.com/ceska.piratska.strana/
  profilePageName: Nějaký název FB profilu
  appId: 1526197851008996

twitter:
  loadSDK: true
  profile: PiratskaStrana

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/

github:
  url: https://github.com/pirati-web/voda.pirati.cz/
  branch: master

#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

github_username:  pirati-web

sass:
  style: compressed
  sass_dir: _sass

theme: jekyll-theme-pirati

markdown: kramdown
theme: jekyll-theme-pirati
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-environment-variables
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/

  program:
    output: true
    permalink: /komunalni-volby/program/:path/

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar:
        - foto
        - personContact
        - people
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
         - garant
         - program

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-7.5.0/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass
